server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: tick #placeholder
    url: jdbc:postgresql://localhost:2345/customer
    password: password #placeholder
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'