server:
  port: 8000


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
        - id: fraud
          uri: lb://fraud
          predicates:
            - Path=/fraud/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

